name: Bug Report
description: Choose this if something is going wrong.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - proxivirus
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "What's the issue?"
    validations:
      required: true
  - type: dropdown
    id: loader-version
    attributes:
      label: What loader are you using?
      options:
        - Datapack (Vanilla)
        - Fabric
        - Quilt
        - Forge
        - Neoforge
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: What Minecraft version are you playing on?
      options:
        - 1.21
        - 1.21.1
        - 1.21.2
        - 1.21.3
        - 1.21.4
        - 1.21.5
        - 1.21.6
        - 1.21.7
        - 1.21.8
        - 1.21.9
        - 1.21.10
        - 1.21.11
        - 26.1
        - My version is not listed :(
    validations:
      required: true
  - type: checkboxes
    id: lastest-version
    attributes:
      label: Are you using the newest version of Superior Stonecutter available?
      options:
        - label: "Yes"
        - label: "No"
